server:
  port: 9191

spring:
  application:
    name: api-gateway
  zipkin:
    baseUrl: http://localhost:9411
    sender:
      # web, rabbit, activemq or kafka
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: CATALOGUE-SERVICE
          uri: http://acme-clothing:8080/
          predicates:
            - Path=/api/catalogue/**
        - id: CATALOGUE-SERVICE-REPLICA
          uri: http://acme-clothing:7070/
          predicates:
            - Path=/api/catalogue-replica/**
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost

management:
  endpoint:
    gateway:
      enabled: true # default value
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info