eureka:
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:8761/eureka
    instance:
        hostname: localhost
logging:
    level:
        ar:
            com:
                challenge:
                    acme:
                        clothing: INFO
        org:
            springframework:
                data:
                    mongodb:
                        repository:
                            Query: TRACE
                            Aggregation: TRACE
                        core:
                            MongoTemplate: TRACE
        root: WARN


management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: health,info,circuitbreakers,circuitbreakerevents,retries,retryevents
    health:
        circuitbreakers:
            enabled: true
        retries:
            enabled: true
resilience4j:
    circuitbreaker:
        configs:
            default:
                failureRateThreshold: 100
                maxWaitDurationInHalfOpenState: 60000
                minimumNumberOfCalls: 4
                permittedNumberOfCallsInHalfOpenState: 5
                registerHealthIndicator: true
                slidingWindowSize: 20
                slidingWindowType: COUNT_BASED
                slowCallDurationThreshold: 60000
                slowCallRateThreshold: 100
                waitDurationInOpenState: 60000
#        instances:
#            order-service:
#                baseConfig: default
    retry:
        configs:
            default:
                enableExponentialBackoff: true
                exponentialBackoffMultiplier: 2
                maxAttempts: 3
                registerHealthIndicator: true
                waitDuration: 1s
#        instances:
#            order-service:
#                baseConfig: default
#                ignoreExceptions: '[io.github.resilience4j.circuitbreaker.CallNotPermittedException]'

server:
  port: 8080

spring:
    application:
        name: catalogue-service
        rabbitmq:
            host: localhost
            password: guest
            port: 5672
            username: guest
        sleuth:
            sampler:
                probability: 1.0
        zipkin:
            baseUrl: http://localhost:9411
            sender:
                type: rabbit
    data:
        mongodb:
            database: acme-clothing
            host: localhost
            port: 27017
    main:
        web-application-type: reactive
    profiles:
        active: prod
