version: "3.8"

volumes:
  data:
    driver: local

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    hostname: localhost
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=$MONGO_DB
    volumes:
      - data:/opt/homebrew/var/mongodb
    networks:
      - main-network
    command: ["--bind_ip", "0.0.0.0"]

  web:
    build:
      #context: ..
      dockerfile: acme-clothing-app/Dockerfile
    image: jproza/acme-clothing
    container_name: acme-clothing
    hostname: localhost
    restart: on-failure
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_APPLICATION_NAME=$APP_NAME
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
    networks:
      - main-network
    command: ["--bind_ip", "0.0.0.0"]

  discovery-server:
    build:
      ##context: ..
      dockerfile: discovery-server/Dockerfile
    image: jproza/discovery-server
    container_name: discovery
    restart: on-failure
    ports:
      - 8761:8761
    environment:
      - SERVER_PORT=8761
    networks:
      - main-network

  api-gateway:
    build:
      ##context: ..
      dockerfile: api-gateway/Dockerfile
    image: jproza/acme-api-gateway
    container_name: api-gateway
    restart: on-failure
    links:
      - discovery-server
      - web
    depends_on:
      - web
      - discovery-server
    ports:
      - 9191:9191
    environment:
      - SERVER_PORT=9191
    networks:
      - main-network

networks:
  main-network:
    name: $NETWORK_NAME
